CREATE DATABASE STOREK;
USE STOREK;

CREATE TABLE PERSONAS(
	ID_PERSONA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DNI VARCHAR(8) NOT NULL UNIQUE,
	NOMBRE VARCHAR(60) NOT NULL,
	APELLIDOS VARCHAR(60) NOT NULL,
	FECHA_NACIMIENTO DATE NOT NULL,
	TELEFONO VARCHAR(60) NULL,
	CORREO VARCHAR(100) NULL,
	SEXO CHAR NOT NULL,
	DIRECCION VARCHAR(255)
);

CREATE TABLE CARGOS(
	ID_CARGO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE_CARGO VARCHAR(60) NOT NULL
);
CREATE TABLE ESTADOS(
	ID_ESTADO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ESTADO VARCHAR(60) NOT NULL
);


CREATE TABLE EMPLEADOS(
	ID_EMPLEADO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ID_PERSONA INT NOT NULL,
	ID_CARGO INT NOT NULL,
	ID_ESTADO INT NOT NULL
);

CREATE TABLE USUARIOS(
	ID_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ID_EMPLEADO INT NOT NULL,
	NOMBRE_USUARIO VARCHAR(45) NOT NULL,
	CLAVE VARCHAR(45) NOT NULL
);

CREATE TABLE PROVEEDORES(
	ID_PROVEEDOR INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ID_PERSONA INT NOT NULL,
	TIPO_EMPRESA VARCHAR(100) NOT NULL,
	DESCRIPCION TEXT NOT NULL
);

 CREATE TABLE CLIENTES(
 	ID_CLIENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
 	ID_PERSONA INT NOT NULL
);

CREATE TABLE TIPO_TARJETA(
	ID_TIPO_TARJETA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE_TARJETA VARCHAR(100) NOT NULL
);

CREATE TABLE VENTAS(
	ID_VENTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ID_USUARIO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_TIPO_TARJETA INT NOT NULL,
	FECHA_VENTA DATETIME NOT NULL,
	IGV DECIMAL(3,2) NOT NULL,
	SUB_TOTAL DECIMAL(8,2) NOT NULL,
	COSTO_VENTA DECIMAL(8,2) NOT NULL
);

CREATE TABLE COMPRAS(
	ID_COMPRA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ID_USUARIO INT NOT NULL,
	FECHA_COMPRA DATETIME NOT NULL,
	ID_PROVEEDOR INT NOT NULL,
	TIPO_TARJETA INT NOT NULL,
	COSTO_COMPRA DECIMAL(8,2) NOT NULL
);

CREATE TABLE CATEGORIAS(
	ID_CATEGORIA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
	DESCRIPCION VARCHAR(255) NULL
);

CREATE TABLE MARCA(
	ID_MARCA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(60) NOT NULL
);

CREATE TABLE MODELO(
	ID_MODELO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(60) NOT NULL
);

CREATE TABLE PRODUCTOS(
	ID_PRODUCTO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
	DESCRIPCION VARCHAR(255) NOT NULL,
	FECHA_FABRICACION DATETIME NOT NULL,
	PRECIO DECIMAL(6,2) NOT NULL,
	STOCK INT NOT NULL,
	ID_CATEGORIA INT NOT NULL,
	ID_MARCA INT NOT NULL,
	ID_MODELO INT NOT NULL
);

CREATE TABLE DETALLES_VENTA(
	ID_DETALLE_VENTA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ID_VENTA INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	UNIDADES INT NOT NULL,
	COSTO_UNIDAD DECIMAL(6,2) NOT NULL,
	DESCUENTO_UNIDAD DECIMAL(4,2) NULL,
	TOTAL DECIMAL(6,2) NOT NULL
);

CREATE TABLE DETALLES_COMPRA(
	ID_DETALLE_COMPRA INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ID_COMPRA INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	UNIDADES INT NOT NULL,
	COSTO_UNIDAD DECIMAL(4,2) NOT NULL,
	TOTAL DECIMAL(6,2) NOT NULL
);





ALTER TABLE EMPLEADOS
ADD CONSTRAINT FK_EMPLEADOSPERSONA
FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE EMPLEADOS
ADD CONSTRAINT FK_EMPLEADOSCARGO
FOREIGN KEY (ID_CARGO) REFERENCES CARGOS(ID_CARGO) ON UPDATE CASCADE;

ALTER TABLE EMPLEADOS
ADD CONSTRAINT FK_EMPLEADOSESTADO
FOREIGN KEY (ID_ESTADO) REFERENCES ESTADOS(ID_ESTADO)ON UPDATE CASCADE;





ALTER TABLE PROVEEDORES
ADD CONSTRAINT FK_PROVEEDORESPERSONA
FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE CASCADE ON UPDATE CASCADE;



ALTER TABLE CLIENTES
ADD CONSTRAINT FK_CLIENTESPERSONA
FOREIGN KEY (ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE USUARIOS
ADD CONSTRAINT FK_USUARIOSEMPLEADO
FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID_EMPLEADO) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE VENTAS
ADD CONSTRAINT FK_VENTASUSUARIO
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE ON UPDATE CASCADE;


ALTER TABLE VENTAS
ADD CONSTRAINT FK_VENTASCLIENTE
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)ON UPDATE CASCADE;

ALTER TABLE VENTAS
ADD CONSTRAINT FK_VENTASTIPOTARJETA
FOREIGN KEY (ID_TIPO_TARJETA) REFERENCES TIPO_TARJETA(ID_TIPO_TARJETA) ON UPDATE CASCADE;


ALTER TABLE DETALLES_VENTA
ADD CONSTRAINT FK_DETALLEVENTAVENTA
FOREIGN KEY (ID_VENTA) REFERENCES VENTAS(ID_VENTA) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE DETALLES_VENTA
ADD CONSTRAINT FK_DETALLEVENTAPRODUCTO
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO) ON UPDATE CASCADE;


ALTER TABLE PRODUCTOS
ADD CONSTRAINT FK_PRODUCTOSCATEGORIA
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA) ON UPDATE CASCADE;

ALTER TABLE PRODUCTOS
ADD CONSTRAINT FK_PRODUCTOSMODELO
FOREIGN KEY (ID_MODELO) REFERENCES MODELO(ID_MODELO) ON UPDATE CASCADE;

ALTER TABLE PRODUCTOS
ADD CONSTRAINT FK_PRODUCTOSMARCA
FOREIGN KEY (ID_MARCA) REFERENCES MARCA(ID_MARCA) ON UPDATE CASCADE;


ALTER TABLE COMPRAS
ADD CONSTRAINT FK_COMPRASUSUARIO
FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON UPDATE CASCADE;

ALTER TABLE COMPRAS
ADD CONSTRAINT FK_COMPRASPROVEEDOR
FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID_PROVEEDOR) ON UPDATE CASCADE;

ALTER TABLE DETALLES_COMPRA
ADD CONSTRAINT FK_DETALLESCOMPRACOMPRA
FOREIGN KEY (ID_COMPRA) REFERENCES COMPRAS(ID_COMPRA) ON UPDATE CASCADE;


ALTER TABLE DETALLES_COMPRA
ADD CONSTRAINT FK_DETALLESPRODUCTO
FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID_PRODUCTO) ON UPDATE CASCADE;



INSERT INTO CARGOS VALUES
(default,'ADMINISTRADOR'),
(default,'REPARTIDOR'),
(default,'DESPACHADOR');

INSERT INTO ESTADOS VALUES
(default,'NO DISPONIBLE'),
(default,'DISPONIBLE');





INSERT INTO PERSONAS VALUES
(default,'11158933','MELIZA CELESTE','JARA JI','1998-08-12','955245622','MELCES.ASD@GMAIL.COM','F','DE ALGUN LUGAR'),
(default,'73958933','JIMENA JOJO','TETE LOLO','1999-02-16','955283222','JIM.TE@GMAIL.COM','F','DE SU CASA'),
(default,'73958111','ANA MARIA','GUIE SALAS','2001-11-08','955283234','ANIT.MA@GMAIL.COM','F','DE NO SE DONDE'),
(default,'73958666','LUCIA EMMA','LUNA LUNA','2001-11-11','955283474','JIM.TE@GMAIL.COM','F','DE SU CASA'),
(default,'73958787','MARCO LUCIO','JALA MUNDO','2002-02-11','955283009','JIM.TE@GMAIL.COM','M','DE SU CASA'),
(default,'73958987','MAICOL MAICELO','MURRIER PERIS','1999-01-20','955283223','JIM.TE@GMAIL.COM','M','DE SU CASA'),
(default,'73958234','RICARDO JULIAN','MENDOZA TORRES','1999-02-16','955283988','JIM.TE@GMAIL.COM','M','DE SU CASA');


INSERT INTO CLIENTES VALUES(default,1),
(default,2),
(default,3),
(default,4);





	




